import NashEquilibrium.Mixed

/-!
# Finite game examples

The examples exercise both layers of the development.  Matching pennies is a
finite game with no pure Nash equilibrium, while the Prisoner's Dilemma has a
pure equilibrium generated by dominant moves.  The mixed examples use the
same native finite-enumeration definitions as the general mixed layer.
-/

namespace NashEquilibrium

open scoped BigOperators

/- In the examples, `false` is the first player/move and `true` is the second. -/

def matchingPennies : Game Bool Bool Int where
  strategies := fun _ => Finset.univ
  payoff := fun p s =>
    if p then
      if s false = s true then 0 else 1
    else
      if s false = s true then 1 else 0
  nonempty_strategies := by
    intro p
    exact Finset.univ_nonempty

def switchCoin (a : Bool) : Bool := !a

theorem switchCoin_ne (a : Bool) : switchCoin a ≠ a := by
  cases a <;> simp [switchCoin]

/-- Matching pennies has no pure Nash equilibrium. -/
theorem matchingPennies_no_pure_nash :
    ¬ ∃ s, IsNash matchingPennies s := by
  rintro ⟨s, hs, hNash⟩
  cases hrow : s false <;> cases hcolumn : s true
  · have hdev := hNash true true (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev
  · have hdev := hNash false true (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev
  · have hdev := hNash false false (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev
  · have hdev := hNash true false (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev

def prisonersDilemma : Game Bool Bool Int where
  strategies := fun _ => Finset.univ
  payoff := fun p s =>
    match s p, s (!p) with
    | false, false => 3
    | true, false => 5
    | false, true => 0
    | true, true => 1
  nonempty_strategies := by
    intro p
    exact Finset.univ_nonempty

def defectProfile : Profile Bool Bool := fun _ => true

theorem prisonersDilemma_defect_is_dominant :
    ∀ p, IsDominant prisonersDilemma p true := by
  intro p
  constructor
  · simp [prisonersDilemma]
  · intro s hs b hb
    cases p <;> cases b <;> cases h0 : s false <;> cases h1 : s true <;>
      simp [prisonersDilemma, deviation, h0, h1]

theorem prisonersDilemma_defect_defect_nash :
    IsNash prisonersDilemma defectProfile := by
  apply dominant_profile_isNash prisonersDilemma defectProfile
  intro p
  simpa [defectProfile] using prisonersDilemma_defect_is_dominant p

/-! The following equivalence makes the four pure profiles explicit. -/

def boolProfileEquiv : (Bool → Bool) ≃ Bool × Bool where
  toFun s := (s false, s true)
  invFun p := fun b => if b then p.2 else p.1
  left_inv := by
    intro s
    funext b
    cases b <;> simp
  right_inv := by
    intro p
    cases p
    simp

def twoProfile (r c : Bool) : Profile Bool Bool :=
  fun p => if p then c else r

lemma boolProfileEquiv_symm_apply (r c : Bool) :
    boolProfileEquiv.symm (r, c) = twoProfile r c := by
  funext p
  cases p <;> simp [boolProfileEquiv, twoProfile]

lemma sum_profile_eq_sum_pair (F : Profile Bool Bool → ℝ) :
    (∑ s : Profile Bool Bool, F s) =
      ∑ r : Bool, ∑ c : Bool, F (twoProfile r c) := by
  calc
    (∑ s : Profile Bool Bool, F s) =
        ∑ x : Bool × Bool, F (boolProfileEquiv.symm x) := by
      exact Fintype.sum_equiv boolProfileEquiv
        (fun s => F s) (fun x => F (boolProfileEquiv.symm x))
        (by intro s; simp)
    _ = ∑ r : Bool, ∑ c : Bool, F (twoProfile r c) := by
      rw [Fintype.sum_prod_type]
      simp [boolProfileEquiv_symm_apply]

def matchingPenniesMixed : MixedGame Bool Bool where
  payoff := fun p s =>
    if p then
      if s false = s true then 0 else 1
    else
      if s false = s true then 1 else 0

noncomputable def uniformBool : MixedProfile Bool Bool := fun _ _ => 1 / 2

lemma uniformBool_isMixedProfile : IsMixedProfile uniformBool := by
  constructor <;> simp [uniformBool]

lemma matchingPennies_uniform_pureDeviation_false (a : Bool) :
    pureDeviationPayoff matchingPenniesMixed uniformBool false a = 1 / 2 := by
  rw [pureDeviationPayoff, sum_profile_eq_sum_pair]
  cases a <;> simp [uniformBool, matchingPenniesMixed,
    twoProfile, opponentWeight]

lemma matchingPennies_uniform_pureDeviation_true (a : Bool) :
    pureDeviationPayoff matchingPenniesMixed uniformBool true a = 1 / 2 := by
  rw [pureDeviationPayoff, sum_profile_eq_sum_pair]
  cases a <;> simp [uniformBool, matchingPenniesMixed,
    twoProfile, opponentWeight]

lemma matchingPennies_uniform_pureDeviation (p a : Bool) :
    pureDeviationPayoff matchingPenniesMixed uniformBool p a = 1 / 2 := by
  cases p
  · exact matchingPennies_uniform_pureDeviation_false a
  · exact matchingPennies_uniform_pureDeviation_true a

lemma matchingPennies_uniform_mixedPayoff (p : Bool) :
    mixedPayoff matchingPenniesMixed uniformBool p = 1 / 2 := by
  rw [mixedPayoff]
  simp_rw [matchingPennies_uniform_pureDeviation]
  simp [uniformBool]

theorem matchingPennies_uniform_mixed_nash :
    IsMixedNash matchingPenniesMixed uniformBool := by
  refine ⟨uniformBool_isMixedProfile, ?_⟩
  intro p a
  rw [matchingPennies_uniform_pureDeviation, matchingPennies_uniform_mixedPayoff]

end NashEquilibrium
