import NashEquilibrium.Mixed
import Mathlib.Algebra.BigOperators.GroupWithZero.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Data.Fintype.BigOperators

/-!
# Finite game examples

The examples exercise both layers of the development.  Matching pennies is a
finite game with no pure Nash equilibrium, while the Prisoner's Dilemma has a
pure equilibrium generated by dominant moves.  Coordination exhibits two
pure equilibria, and the mixed examples include the uniform equilibria of
matching pennies and rock-paper-scissors.
-/

namespace NashEquilibrium

open scoped BigOperators

/- In the examples, `false` is the first player/move and `true` is the second. -/

def matchingPennies : Game Bool Bool Int where
  strategies := fun _ => Finset.univ
  payoff := fun p s =>
    if p then
      if s false = s true then 0 else 1
    else
      if s false = s true then 1 else 0
  nonempty_strategies := by
    intro p
    exact Finset.univ_nonempty

def switchCoin (a : Bool) : Bool := !a

theorem switchCoin_ne (a : Bool) : switchCoin a ≠ a := by
  cases a <;> simp [switchCoin]

/-- Matching pennies has no pure Nash equilibrium. -/
theorem matchingPennies_no_pure_nash :
    ¬ ∃ s, IsNash matchingPennies s := by
  rintro ⟨s, hs, hNash⟩
  cases hrow : s false <;> cases hcolumn : s true
  · have hdev := hNash true true (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev
  · have hdev := hNash false true (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev
  · have hdev := hNash false false (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev
  · have hdev := hNash true false (by simp [matchingPennies])
    simp [matchingPennies, deviation, hrow, hcolumn] at hdev

def prisonersDilemma : Game Bool Bool Int where
  strategies := fun _ => Finset.univ
  payoff := fun p s =>
    match s p, s (!p) with
    | false, false => 3
    | true, false => 5
    | false, true => 0
    | true, true => 1
  nonempty_strategies := by
    intro p
    exact Finset.univ_nonempty

def defectProfile : Profile Bool Bool := fun _ => true

theorem prisonersDilemma_defect_is_dominant :
    ∀ p, IsDominant prisonersDilemma p true := by
  intro p
  constructor
  · simp [prisonersDilemma]
  · intro s hs b hb
    cases p <;> cases b <;> cases h0 : s false <;> cases h1 : s true <;>
      simp [prisonersDilemma, deviation, h0, h1]

theorem prisonersDilemma_defect_defect_nash :
    IsNash prisonersDilemma defectProfile := by
  apply dominant_profile_isNash prisonersDilemma defectProfile
  intro p
  simpa [defectProfile] using prisonersDilemma_defect_is_dominant p

/-! Coordination has two pure Nash equilibria, one at each coordinated
profile. -/

def coordination : Game Bool Bool Int where
  strategies := fun _ => Finset.univ
  payoff := fun _ s => if s false = s true then 1 else 0
  nonempty_strategies := by
    intro p
    exact Finset.univ_nonempty

def coordinationFalse : Profile Bool Bool := fun _ => false

def coordinationTrue : Profile Bool Bool := fun _ => true

theorem coordination_false_false_nash : IsNash coordination coordinationFalse := by
  refine ⟨?_, ?_⟩
  · intro p
    simp [coordination, coordinationFalse]
  · intro p a ha
    cases p <;> cases a <;> simp [coordination, coordinationFalse, deviation]

theorem coordination_true_true_nash : IsNash coordination coordinationTrue := by
  refine ⟨?_, ?_⟩
  · intro p
    simp [coordination, coordinationTrue]
  · intro p a ha
    cases p <;> cases a <;> simp [coordination, coordinationTrue, deviation]

/-!
The next example records the terminology boundary explicitly.  With constant
payoffs, the generalized condition is vacuous, so a potential may still rise
on a payoff-neutral move.  The standard bidirectional condition rejects this
same potential.
-/

def neutralDeviationGame : Game Bool Bool Int where
  strategies := fun _ => Finset.univ
  payoff := fun _ _ => 0
  nonempty_strategies := by
    intro p
    exact Finset.univ_nonempty

def neutralDeviationPotential : Profile Bool Bool → Bool := fun s => s false

def neutralBase : Profile Bool Bool := fun _ => false

theorem neutralDeviationGame_is_generalized :
    IsGeneralizedOrdinalPotential neutralDeviationGame neutralDeviationPotential := by
  intro s p a hs ha himprove
  simp [neutralDeviationGame] at himprove

theorem neutralDeviationPotential_not_standard :
    ¬ IsOrdinalPotential neutralDeviationGame neutralDeviationPotential := by
  intro hstandard
  have hpotential :
      neutralDeviationPotential neutralBase <
        neutralDeviationPotential (deviation neutralBase false true) := by
    simp [neutralDeviationPotential, neutralBase, deviation]
  have himprove :
      neutralDeviationGame.payoff false neutralBase <
        neutralDeviationGame.payoff false (deviation neutralBase false true) :=
    (hstandard (s := neutralBase) (p := false) (a := true)
      (by intro p; simp [neutralDeviationGame, neutralBase])
      (by simp [neutralDeviationGame])).mpr hpotential
  simp [neutralDeviationGame] at himprove

/-! The following equivalence makes the four pure profiles explicit. -/

def boolProfileEquiv : (Bool → Bool) ≃ Bool × Bool where
  toFun s := (s false, s true)
  invFun p := fun b => if b then p.2 else p.1
  left_inv := by
    intro s
    funext b
    cases b <;> simp
  right_inv := by
    intro p
    cases p
    simp

def twoProfile (r c : Bool) : Profile Bool Bool :=
  fun p => if p then c else r

lemma boolProfileEquiv_symm_apply (r c : Bool) :
    boolProfileEquiv.symm (r, c) = twoProfile r c := by
  funext p
  cases p <;> simp [boolProfileEquiv, twoProfile]

lemma sum_profile_eq_sum_pair (F : Profile Bool Bool → ℝ) :
    (∑ s : Profile Bool Bool, F s) =
      ∑ r : Bool, ∑ c : Bool, F (twoProfile r c) := by
  calc
    (∑ s : Profile Bool Bool, F s) =
        ∑ x : Bool × Bool, F (boolProfileEquiv.symm x) := by
      exact Fintype.sum_equiv boolProfileEquiv
        (fun s => F s) (fun x => F (boolProfileEquiv.symm x))
        (by intro s; simp)
    _ = ∑ r : Bool, ∑ c : Bool, F (twoProfile r c) := by
      rw [Fintype.sum_prod_type]
      simp [boolProfileEquiv_symm_apply]

def matchingPenniesMixed : MixedGame Bool Bool where
  payoff := fun p s =>
    if p then
      if s false = s true then 0 else 1
    else
      if s false = s true then 1 else 0

noncomputable def uniformBool : MixedProfile Bool Bool := fun _ _ => 1 / 2

lemma uniformBool_isMixedProfile : IsMixedProfile uniformBool := by
  constructor <;> simp [uniformBool]

lemma matchingPennies_uniform_pureDeviation_false (a : Bool) :
    pureDeviationPayoff matchingPenniesMixed uniformBool false a = 1 / 2 := by
  rw [pureDeviationPayoff, sum_profile_eq_sum_pair]
  cases a <;> simp [uniformBool, matchingPenniesMixed,
    twoProfile, opponentWeight]

lemma matchingPennies_uniform_pureDeviation_true (a : Bool) :
    pureDeviationPayoff matchingPenniesMixed uniformBool true a = 1 / 2 := by
  rw [pureDeviationPayoff, sum_profile_eq_sum_pair]
  cases a <;> simp [uniformBool, matchingPenniesMixed,
    twoProfile, opponentWeight]

lemma matchingPennies_uniform_pureDeviation (p a : Bool) :
    pureDeviationPayoff matchingPenniesMixed uniformBool p a = 1 / 2 := by
  cases p
  · exact matchingPennies_uniform_pureDeviation_false a
  · exact matchingPennies_uniform_pureDeviation_true a

lemma matchingPennies_uniform_mixedPayoff (p : Bool) :
    mixedPayoff matchingPenniesMixed uniformBool p = 1 / 2 := by
  rw [mixedPayoff]
  simp_rw [matchingPennies_uniform_pureDeviation]
  simp [uniformBool]

theorem matchingPennies_uniform_mixed_nash :
    IsMixedNash matchingPenniesMixed uniformBool := by
  refine ⟨uniformBool_isMixedProfile, ?_⟩
  intro p a
  rw [matchingPennies_uniform_pureDeviation, matchingPennies_uniform_mixedPayoff]

/-! Rock-paper-scissors has a uniform mixed equilibrium. -/

inductive RPS : Type
  | rock
  | paper
  | scissors
  deriving DecidableEq

instance : Fintype RPS where
  elems := {.rock, .paper, .scissors}
  complete := by
    intro a
    cases a <;> simp

instance : Nonempty RPS := ⟨.rock⟩

@[simp] lemma rps_univ : (Finset.univ : Finset RPS) = {.rock, .paper, .scissors} := by
  rfl

def rpsBeats : RPS → RPS → Bool
  | .rock, .scissors => true
  | .paper, .rock => true
  | .scissors, .paper => true
  | _, _ => false

def rpsPayoff : Bool → Profile Bool RPS → ℝ := fun p s =>
  if s false = s true then 0
  else if rpsBeats (s false) (s true) then
    if p then -1 else 1
  else if p then 1 else -1

def rockPaperScissors : MixedGame Bool RPS where
  payoff := rpsPayoff

noncomputable def uniformRPS : MixedProfile Bool RPS :=
  uniformMixedProfile

def rpsProfileEquiv : (Bool → RPS) ≃ RPS × RPS where
  toFun s := (s false, s true)
  invFun p := fun b => if b then p.2 else p.1
  left_inv := by
    intro s
    funext b
    cases b <;> simp
  right_inv := by
    intro p
    cases p
    simp

def twoRPSProfile (r c : RPS) : Profile Bool RPS :=
  fun p => if p then c else r

lemma rpsProfileEquiv_symm_apply (r c : RPS) :
    rpsProfileEquiv.symm (r, c) = twoRPSProfile r c := by
  funext p
  cases p <;> simp [rpsProfileEquiv, twoRPSProfile]

lemma sum_rps_profile_eq_sum_pair (F : Profile Bool RPS → ℝ) :
    (∑ s : Profile Bool RPS, F s) =
      ∑ r : RPS, ∑ c : RPS, F (twoRPSProfile r c) := by
  calc
    (∑ s : Profile Bool RPS, F s) =
        ∑ x : RPS × RPS, F (rpsProfileEquiv.symm x) := by
      exact Fintype.sum_equiv rpsProfileEquiv
        (fun s => F s) (fun x => F (rpsProfileEquiv.symm x))
        (by intro s; simp)
    _ = ∑ r : RPS, ∑ c : RPS, F (twoRPSProfile r c) := by
      rw [Fintype.sum_prod_type]
      simp [rpsProfileEquiv_symm_apply]

lemma uniformRPS_isMixedProfile : IsMixedProfile uniformRPS := by
  exact uniformMixedProfile_isMixedProfile

lemma rps_uniform_pureDeviation_false (a : RPS) :
    pureDeviationPayoff rockPaperScissors uniformRPS false a = 0 := by
  rw [pureDeviationPayoff, sum_rps_profile_eq_sum_pair]
  cases a <;>
    simp [uniformRPS, uniformMixedProfile, rockPaperScissors, rpsPayoff,
      rpsBeats, twoRPSProfile, opponentWeight, rps_univ]

lemma rps_uniform_pureDeviation_true (a : RPS) :
    pureDeviationPayoff rockPaperScissors uniformRPS true a = 0 := by
  rw [pureDeviationPayoff, sum_rps_profile_eq_sum_pair]
  cases a <;>
    simp [uniformRPS, uniformMixedProfile, rockPaperScissors, rpsPayoff,
      rpsBeats, twoRPSProfile, opponentWeight, rps_univ]

lemma rps_uniform_pureDeviation (p : Bool) (a : RPS) :
    pureDeviationPayoff rockPaperScissors uniformRPS p a = 0 := by
  cases p
  · exact rps_uniform_pureDeviation_false a
  · exact rps_uniform_pureDeviation_true a

lemma rps_uniform_mixedPayoff (p : Bool) :
    mixedPayoff rockPaperScissors uniformRPS p = 0 := by
  rw [mixedPayoff]
  simp_rw [rps_uniform_pureDeviation]
  simp [uniformRPS, uniformMixedProfile]

theorem rps_uniform_mixed_nash :
    IsMixedNash rockPaperScissors uniformRPS := by
  refine ⟨uniformRPS_isMixedProfile, ?_⟩
  intro p a
  rw [rps_uniform_pureDeviation, rps_uniform_mixedPayoff]

end NashEquilibrium
